# sklearn.impute
Les transformateurs permettant de nettoyer nos dataset en éliminant ou rmplaçant les valeurs manquantes dans le dataset 

# SIMPLE IMPUTER
Remplace toutes les valeurs manquantes par une valeur statistique
 - missing_values
 - strategy : mean , median , most_frequent ,constant
 - fill_value(pour constant)

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.linear_model import SGDClassifier

In [3]:
from sklearn.impute import SimpleImputer

In [3]:
X = np.array([[10,3],
             [0,4],
             [5,3],
             [np.nan , 3]])

In [9]:
imputer= SimpleImputer(missing_values=np.nan,
             strategy='mean') # on peut avoir np.inf ...
imputer.fit_transform(X)

array([[10.,  3.],
       [ 0.,  4.],
       [ 5.,  3.],
       [ 5.,  3.]])

 Tranform(X_test) remplace les valeurs manquantes par les moyennes calculées sur X_train 

In [10]:
X_test =np.array([[12,5],
                 [40,2],
                 [5,5],
                 [np.nan, np.nan]])
imputer.transform(X_test)

array([[12.  ,  5.  ],
       [40.  ,  2.  ],
       [ 5.  ,  5.  ],
       [ 5.  ,  3.25]])

# KNN Imputer

Il remplace toutes les valeurs manquantes par des valeurs des plus proches voisins  near neighbors , nombre de voisins optimal

In [4]:
from sklearn.impute import KNNImputer

In [5]:
X = np.array([[1,100],
             [2,30],
             [3,15],
             [np.nan,20]])

In [6]:
imputer = KNNImputer(n_neighbors=1)
imputer.fit_transform(X)

array([[  1., 100.],
       [  2.,  30.],
       [  3.,  15.],
       [  3.,  20.]])

 # MissingIndicator
 il utilise des variablesbooléenne qui indique l ábsence de valeurs dans le dataset 
  parfois le manque d'infos est une information 

In [7]:
from sklearn.impute import MissingIndicator

In [8]:
X = np.array([[1,100],
             [2,30],
             [3,15],
             [np.nan,np.nan]])

In [9]:
MissingIndicator().fit_transform(X)

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True]])